### ISSUE TITLE
Invalid "form feed" character causing 404 errors

### ISSUE THREAD

**Issue by eczheng** [pkp/jatsTemplate#19]
We recently encountered a galley with an invalid "form feed" character, which caused the OAI request to return a 404 error. 

We found that this line can be added to the plugin code, to filter it out:

`$xml = str_replace(array("\f"), '', $this->toXml($record));`

Could it be added to the next plugin release? Thank you!

**Comment by asmecher** [comment]
@eczheng, could you provide a little more information about e.g. where the form feed appeared, and if known, how it got into the system? (For completeness, also please include information about the installation -- your OJS, JATS template, and OAI jats plugin versions.)

**Comment by asmecher** [comment]
Thanks, @eczheng -- where in the JATS XML is the form feed appearing?

**Comment by eczheng** [comment]
Thanks, @asmecher, it's appearing where there are page breaks; between the footer of the previous page, and the header of the next page.

For example (see lines 84, 114, 145 etc.): [problemXML.txt](https://github.com/pkp/jatsTemplate/files/8318802/problemXML.txt)
Please note that the character is visible in Notepad & Notepad++.  I couldn't see it while using Atom. Not sure about other text editors.

**Comment by asmecher** [comment]
@eczheng, this will be coming from your PDF text extraction tools, which are configured in `config.inc.php` in the `search` section. The examples that ship in `config.inc.php` include some measures to remove control characters:
```
; PDF
; index[application/pdf] = "/usr/bin/pstotext -enc UTF-8 -nopgbrk %s - | /usr/bin/tr '[:cntrl:]' ' '"
; index[application/pdf] = "/usr/bin/pdftotext -enc UTF-8 -nopgbrk %s - | /usr/bin/tr '[:cntrl:]' ' '"

; PostScript
; index[application/postscript] = "/usr/bin/pstotext -enc UTF-8 -nopgbrk %s - | /usr/bin/tr '[:cntrl:]' ' '"
; index[application/postscript] = "/usr/bin/ps2ascii %s | /usr/bin/tr '[:cntrl:]' ' '"
```

**Comment by eczheng** [comment]
Thanks so much, @asmecher! I've passed this onto our programming team, and they think it'll work. Much appreciated.

**Comment by asmecher** [comment]
Hope it helps! I'm closing this issue in the meantime.
