### ISSUE TITLE
jats xml schemas for contributors

### ISSUE THREAD

**Issue by odolany** [pkp/jatsTemplate#7]
There seems to be an inconsistency between JATS plugins output and nlm specification for authors:

opening tags in current  JATS oai result:
```
<contrib-group content-type="author" >
<contrib>
<name name-style="western">
```
(author is not among content-types)

Specification:
https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-pww0.html
https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-n3w0.html

correct (?) opening tags in oai result?
```
<contrib-group>
<contrib contrib-type="author">
<name name-style="western">
```

hope it helps

**Comment by asmecher** [comment]
Thanks, @odolany; I've raised this in a related Gitlab issue (unfortunately it's closed but I'll attempt to sync the relevant info up over here too). Stay tuned. https://gitlab.erudit.org/coalitionpublica/ojs3-jats-for-cjoe/issues/38

**Comment by odolany** [comment]
thanks for the answer!
one more thing I noticed as for generated xml is the lacking xml:lang attribute for <abstract> element
https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-ba20.html

where I test it, the richer language data shows correctly for Dublin Core version of metadata

**Comment by asmecher** [comment]
@odolany, a comment from Fabio B, who works with us on some of these elements:
> The proposed structure is following JATS4M (Texture), there are several discussions about this subject in Texture.
>
>At this moment the current version of Texture supports the following data structure.
>
>Texture DAR definition (https://github.com/substance/dar/blob/master/DarArticle.md#contrib-group)
>
>We are open to discuss about this topic and revert our previous decisions but it should be made in accordance with the other stakeholders. The good news is that we are discussing these things at this moment with all the Substance Consortium members.

**Comment by asmecher** [comment]
> one more thing I noticed as for generated xml is the lacking xml:lang attribute for "abstract" element
https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-ba20.html

This is possibly due to the OAIJats plugin, not the JATSTemplate plugin. You're looking at the OAI output, right?

It's currenlty coded not to include the `xml:lang` on `<abstract>` elements unless the abstract language differs from the article's main locale. Is that the behavior you're seeing?

**Comment by odolany** [comment]
ok then. all's good I guess. 
As you said I inspected oai output and xml:lang was omitted as intended from your description.
thanks for the info on Texture etc. i'll let all here in CEJSH et al know and we'll adjust to new specs.

**Comment by asmecher** [comment]
Thanks, @odolany, I'll close this one for now.
